src/Main.bas, src/Manifest.xml, src/TabWindow.bas, src/TabWindow.bi, src/VisualFBEditor.bas
Fixed crashed when click "Form" bottom while open .bas file
Saving find forms for each code editor
=> Fixed crashed when click "Form" bottom while open .bas file

src/Main.bas, src/TabWindow.bas, src/frmOptions.frm
I did this twice. It is the same change and I remove it and add again
=> Fixed: Improve the speed of function IndexOf

src/TabWindow.bas
Please shwitch off  AutoComplete in setting if you do not like this function
=> Fixed:  Auto Complete words  by press Enter Key.

Examples/MDIForm/MDIChild.frm, Examples/MDIForm/MDIList.frm, Examples/MDIForm/MDIMain.frm
1. Apply new Form template
2. Delete compilation warning
=> Improve MDIForm Example

Examples/MDINotepad/MDIMain.frm, Examples/MDINotepad/frmFileSearch.frm, Examples/MDINotepad/frmHash.frm
Corrected time units from milliseconds to seconds
=> Fixed time units for MDI Notepad Example

Examples/MDIForm/README.md, Examples/MDINotepad/README.md, Examples/MDIScintilla/README.md, Examples/MDIScintillaControl/README.md
MDIForm, MDINotepad, MDIScintilla, MDIScintillaControl, Bass
=> Add README for Examples

src/frmSplash.frm
How to add a waiting cursor in txtCode windows when loadinng a big file?
=> Add: Add waiting cursor in Splash forms

src/Main.bas, src/TabWindow.bas
Remove the code for "WString*200" also
=> Fixed: IntelliSense bug "TYPE AS"

src/VisualFBEditor.bas
Now working on Muilt screen fine.
=> Add: Showing the sub windows on the same screen of main form.

src/frmFind.frm
For avoid replace all in project by mistake
=> Added: Should Confirm first before Replace All in Project

src/frmFind.frm
=> Fixed:  Search out of the range after replace in procedure

src/Main.bi, src/frmFind.bi, src/frmFind.frm
1. Layout fine-tuning
2. Remove static events
3. Used HK() to show shortcut
=> Update Find & Replace

src/frmFind.frm
=> Fixed: Find and replace within Selection text

src/EditControl.bas, src/VisualFBEditor.bas, src/frmFind.bi, src/frmFind.frm
The last item will be replace at the last. Someone could be help this?
=> Fixed: Find and Replace in Projects

Templates/Files/Form.frm, Templates/Files/Form_3D.frm, src/Main.bas, src/Main.bi
We can now display the local caption when designing the forms.
=> Added: Add support for multiple languages

src/TabWindow.bas
=> Added: add default events to HTTPServer, HTTPConnection, PrintDocument

src/Main.bas
The compiler error is different with a Unicode file name.
=> Fixed: Cannot display the first compiler error with a Unicode file name

src/Main.bas, src/frmFind.frm
The information will merge into one single line sometimes in bit 64
=> Updated: Updated Main.bas

Settings/Languages/chinese.lng, src/Main.bas, src/TabWindow.bas
Now missing some information when compiling short file. The others is OK now
`  'missing some information when compiling short file.
' draw vector graphic on FBGFX Image
Const As Lon iWidth  = 150
Const As Long iHeight = 150
Print iHeight
`
=> Fixed：Certain compilation error messages were inaccurately shown.

src/TabWindow.bas
I think the control cboFunction did not get the DPI change message when create a new TABCODE
=> Fixed:  btnCodeandForm missing after change from one screen to another screen

src/EditControl.bas
This is working fine with Chinese on Windows OS.
=> Fixed: Improve the support of UTF8 and UTF8(BOM)

Examples/DeviceExplorer/Languages/Chinese (Simplified).lng, Examples/DeviceExplorer/Languages/english.html, Examples/DeviceExplorer/Languages/english.lng, Examples/DeviceExplorer/frmDeviceExplorer.frm, Examples/MultipleDisplay/frmDisplay.frm, src/Main.bas
Fixed: MainNode caption not refreshed when a file is set as the main in Folders.
=> Fixed: MainNode caption not refreshed when a file is set as the main in Folders.

src/Debug.bas, src/EditControl.bas, src/TabWindow.bas
Still not fix the Shell() function issue in Linux OS.
=> Fixed: Display the error message in Sub PipeCmd.

src/Main.bas, src/TabWindow.bas
GetFolderName doesn't work with "tmpdir/" and GetFileName doesn't work with "C:tmpFile.txt".
=> Fixed：improve function GetFileName, GetFolderName

src/Main.bas, src/TabWindow.bas
=> Added: Create a Markdown-style wiki.

src/EditControl.bas
Fix the bug and UTF-8 without BOM support
=> Improve: UTF-8 without BOM support in LoadFromFile function

src/Main.bas, src/TabWindow.bas, src/TabWindow.bi, src/VisualFBEditor.bas
The AI like to use .SetBounds(0, 0, 433, 85), Now Fixed
=> Added: Unicode-Hex conversion functions.

Help/AI prompt/KnowledgeBase/VisualFBEditor IDE Environment.md, Help/AI prompt/MyFbFramework GUI Form Interface Guidelines.json
An AI prompt refers to a specific input or instruction given to an artificial intelligence system to generate a desired output MFF Forms.
=> AI prompt  for MFF

src/EditControl.bas
Now skipping code changes like " _ " or "data" for "ChangeCollapsibility i" only, and consider applying this to lines not starting with keywords.
=> Fixed: Improved read source code file speed.
